var num1 = 5;
var num2 = 6;
var sum = num1 + num2;
var sub = num1 - num2;
var mul = num1 * num2;
var div = num1 / num2;
var mod = num1 % num2;
alert(sum);
alert(sub);
alert(mul);
alert(div);
alert(mod);